services:
  - type: static
    name: br-publications-frontend
    env: static
    buildCommand: npx vite build
    publishDir: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://br-publications-backend.onrender.com
      - key: VITE_API_URL
        value: https://br-publications-backend.onrender.com
      - key: VITE_GOOGLE_CLIENT_ID
        value: 475289564338-bjoieqnbf2abi140onried6ao9getu4a.apps.googleusercontent.com
